name: flutter_firebase
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2

  #core
  easy_localization: ^3.0.2
  flutter_riverpod: ^2.3.6
  kartal: ^3.2.0
  very_good_analysis: ^5.0.0+1
  equatable: ^2.0.5

  #firebasse
  cloud_firestore: ^4.8.4
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  firebase_ui_auth: ^1.6.2
  firebase_ui_oauth_google: ^1.2.7

  #utility
  animated_text_kit: ^4.2.2
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/



  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

